# 一、ndarry

## 1.ndarry特性

### 多维性

In [2]:
import numpy as np

创建0维数组

In [3]:
arr = np.array(5)
print(arr)
print("arr的维度:",arr.ndim)  #number of dimensions

5
arr的维度: 0


创建一维数组

In [4]:
arr = np.array([1,2,3])
print(arr)
print("arr的维度:",arr.ndim)

[1 2 3]
arr的维度: 1


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("arr的维度:",arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr的维度: 2


### 同质性

In [6]:
arr = np.array([1,"hello"])  #不同数据类型会转化成相同类型
print(arr)

['1' 'hello']


In [7]:
arr = np.array([1,2.5])
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
8
int64
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## 3.ndarray 创建


In [9]:
list = [4,5,6,7,8]
arr = np.array(list,dtype = np.float64) #转换数据类型
print(arr.ndim)
print(arr)

1
[4. 5. 6. 7. 8.]


In [10]:
arr1 = np.copy(arr) #复制过来
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6. 7. 8.]
[8. 5. 6. 7. 8.]
[4. 5. 6. 7. 8.]


In [11]:
arr = np.zeros((2,3),dtype = int) #定义全0数组
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [12]:
arr = np.ones((3,7),dtype = int)
print(arr)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [13]:
arr = np.empty((2,9))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
arr = np.full((3,4),2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [15]:
arr1 = np.zeros_like(arr) #形状相同
print(arr1)
arr2 = np.empty_like(arr)
print(arr2)
arr3 = np.ones_like(arr)
print(arr3)
arr4 = np.full_like(arr,444)
print(arr4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[444 444 444 444]
 [444 444 444 444]
 [444 444 444 444]]


In [16]:
arr = np.arange(1,10,1) #起始 结尾 步长
print(arr)
arr = np.arange(2,10,2)
print(arr)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [17]:
arr = np.linspace(0,10,5,dtype=int) #等间隔
print(arr)

[ 0  2  5  7 10]


In [18]:
arr = np.logspace(0,4,3, base = 2) #2的0、2、4次方
print(arr)

[ 1.  4. 16.]


### 特殊矩阵

In [19]:
arr = np.eye(3,4,dtype = int) #单位矩阵
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [20]:
arr = np.diag([1,2,3]) #对角矩阵
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 随机数组生成

In [21]:
arr = np.random.rand(2,3) #0-1范围
print(arr)

[[0.57672046 0.09289475 0.81996998]
 [0.31844458 0.3743187  0.2010211 ]]


In [22]:
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[5.04281463 4.17805448 5.20990558]
 [3.38888336 4.5716975  3.22623387]]


In [23]:
arr = np.random.randint(3,6,(2,3))
print(arr)

[[5 4 4]
 [5 5 4]]


In [24]:
arr = np.random.randn(2,3) #正态分布 两边概率小，中间概率大
print(arr)

[[-0.49311617 -0.76902606 -0.0210676 ]
 [ 0.05989968  1.34364304  0.57234624]]


In [25]:
np.random.seed(20) #设置随机种子 每次运行都一样
arr = np.random.randint(1,10,(2,5))
print(arr)


[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4.ndarray的数据类型
布尔bool 整数int uint 浮点数float 复数complex

In [26]:
arr = np.array([1,2,0,1,0],dtype = np.bool)
arr1 = np.array([1,2,125,0],dtype = np.int8)
print(arr)
print(arr1)

[ True  True False  True False]
[  1   2 125   0]


## 5.索引与切片

In [27]:
arr = np.random.randint(1,100,10)
print(arr)
print(arr[0])
print(arr[:])
print(arr[2:8])
print(arr[slice(2,8,4)])
print(arr[arr>50])
print(arr[(arr>10)&(arr<70)])

[17 63 17  8 99  7 27 14 76 59]
17
[17 63 17  8 99  7 27 14 76 59]
[17  8 99  7 27 14]
[17 27]
[63 99 76 59]
[17 63 17 27 14 59]


In [28]:
arr = np.random.randint(1,100,(4,8))
print(arr)

[[26  4 75 76 62 78 84 58]
 [95 33 11  7 76 19  4 78]
 [18 44 17 19 80 91 60 72]
 [76 30 46  7 64 79 25 19]]


In [29]:
print(arr[1,3]) #精确索引
print(arr[:,:])
print(arr[1,:])
print(arr[1,2:4])
print(arr[arr>50])
print(arr[2])
print(arr[2][arr[2]>50])
print(arr[:,3])
print(arr[:,3][arr[:,3]>30])

7
[[26  4 75 76 62 78 84 58]
 [95 33 11  7 76 19  4 78]
 [18 44 17 19 80 91 60 72]
 [76 30 46  7 64 79 25 19]]
[95 33 11  7 76 19  4 78]
[11  7]
[75 76 62 78 84 58 95 76 78 80 91 60 72 76 64 79]
[18 44 17 19 80 91 60 72]
[80 91 60 72]
[76  7 19  7]
[76]


## 6.ndarry的运算

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(b-a)
print(a*b)
print(a**2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[1 4 9]


In [31]:
a = [1,2,3]
b = [4,5,6]
print(a+b)
for i in range(len(a)):
    b[i] = a[i] + b[i]
    print(a[i])
print(b)

[1, 2, 3, 4, 5, 6]
1
2
3
[5, 7, 9]


In [32]:
#数组与数组算术运算
a = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
b = np.array([[4, 5, 6],[7, 8, 9],[1,2,3]])
print(a + b)
print(b - a)
print(a * b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[ 3  3  3]
 [ 3  3  3]
 [-6 -6 -6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [33]:
#数组与标量算术运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [34]:
 a = np.array([[1,1,1],[1,1,1],[1,1,1]])
 b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 print(a@b)
 print(a*b)

[[12 15 18]
 [12 15 18]
 [12 15 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 2.1numpy基本数学函数

In [35]:
#平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))

3.0
[1. 2. 3.]


In [36]:
#计算指数
print(np.exp(1))
print(np.exp(0))

2.718281828459045
1.0


In [37]:
#计算自然对数
print(np.log(2.718281))

0.999999695226903


In [38]:
#计算三角函数正弦余弦
print(np.sin(np.pi/2))

1.0


In [39]:
#计算绝对值
arr = np.array([-1,2,-5])
print(np.abs(arr))

[1 2 5]


In [40]:
#计算a的b次幂
print(np.power(arr,2))

[ 1  4 25]


In [41]:
#四舍五入
print(np.round([3.2,4.5,8.1,9.9]))

[ 3.  4.  8. 10.]


In [42]:
#向下向上取整
arr = np.array([2.3,35.1,77.9])
print(np.ceil(arr))
print(np.floor(arr))

[ 3. 36. 78.]
[ 2. 35. 77.]


In [43]:
#检测缺失值NAN
np.isnan([1,3,np.nan,3])

array([False, False,  True, False])

## 2.2numpy基本统计函数

求和 平均值 中位数 标准差 方差 最大最小 累积和 累积差。

In [44]:
arr = np.random.randint(1,20,8)
print(arr)


[ 2 15 11  4 19  7 10 15]


In [45]:
#求和
print(np.sum(arr))

83


In [46]:
#计算平均值
print(np.mean([1,2,3]))

2.0


In [47]:
#计算中位数
print(np.median([1,2,3,5,7,8]))
print(np.median(arr))

4.0
10.5


In [48]:
#计算方差and标准差
print(np.var([1,2,3]))
print(np.std([1,2,3]))  #开根


0.6666666666666666
0.816496580927726


In [49]:
#计算最大最小
print(arr)
print(np.max(arr),np.argmax(arr)) #索引位置
print(np.min(arr))

[ 2 15 11  4 19  7 10 15]
19 4
2


In [50]:
#中位数
print(np.median(([1,2,3]))) #这是中位数

np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
print(np.median(arr))


2.0
[44 47 64 67]
55.5


In [51]:
#分位数
print(np.percentile(arr,50)) #取50%
arr = np.array([1,4,5,6,8,9])
print(arr)
print(np.percentile(arr,30))

55.5
[1 4 5 6 8 9]
4.5


In [52]:
#累积和 累积ji
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 比较函数

In [53]:
print(np.greater([2,3,4,5,6,7],4))

[False False False  True  True  True]


In [54]:
print(np.less([2,3,4,5,6,7],4))

[ True  True False False False False]


In [55]:
print(np.equal([3,4,5,6,7,8],4))

[False  True False False False False]


In [56]:
print(np.equal([3,4,5],[4,4,4]))

[False  True False]


In [57]:
print(np.logical_and([0,0],[1,1])) #都真为真
print(np.logical_or([0,0],[1,1]))  #有真就真
print(np.logical_not([1,0])) #取反

[False False]
[ True  True]
[False  True]


In [58]:
print(np.any([0,0,0,1])) #只要有一个 为true
print(np.all([0,0,1,1,1])) #要全部为true

True
False


In [59]:
# print(np.where([条件，符合，不符合]))
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.where(arr<3,arr,0))
print(np.where(arr<=3,1,0))

[1 2 0 0 0 0 0 0 0]
[1 1 1 0 0 0 0 0 0]


In [60]:
score = np.random.randint(50,100,20)
print(score)
print(np.where(score<60,'不及格',np.where(score<80,'良好','优秀')))

[53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [61]:
score = np.random.randint(50,100,20)
print(np.select([score<60,(score>=60)&(score<80),score>=80],['不及格','良好','优秀'],default='未知'))

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '优秀' '不及格' '良好' '优秀' '良好' '优秀' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


In [62]:
#排序函数
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
#arr.sort() 会改变原数组
print(np.sort(arr))
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [63]:
#去重
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [64]:
#数组拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [65]:
#数组分割
print(arr)
print(np.split(arr,5))
print(np.split(arr,[6,12,18]))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[array([45, 48, 65, 68]), array([68, 10, 84, 22]), array([37, 88, 71, 89]), array([89, 13, 59, 66]), array([40, 88, 47, 89])]
[array([45, 48, 65, 68, 68, 10]), array([84, 22, 37, 88, 71, 89]), array([89, 13, 59, 66, 40, 88]), array([47, 89])]


In [66]:
#调整数组形状
print(arr)
print(np.reshape(arr,[4,5]))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [67]:
#某城市一天的最高气温 计算平均最低最高,计算温度超过30的天数
import numpy as np
temps = np.array([28,30,29,31,32,30,29])
print(temps)
print('平均气温:')
print('%.3f'%np.mean(temps))
print('最高气温:')
print(np.max(temps))
print('最低气温:')
print(np.min(temps))
print('气温超过30°C的天数:')
print(len(temps[temps>30]))
print(np.where(temps>30,1,0))
print(np.cumsum(np.where(temps>30,1,0))[-1])
print(np.count_nonzero(temps>30))

[28 30 29 31 32 30 29]
平均气温:
29.857
最高气温:
32
最低气温:
28
气温超过30°C的天数:
2
[0 0 0 1 1 0 0]
2
2


In [68]:
#学生成绩统计 平均分,中位数,标准差,方差,转化为百分制
score = np.array([85,90,78,92,88])
print(score)
print(np.mean(score))
print(np.median(score))
print(np.std(score))
print(np.var(score))
print(score/10)

[85 90 78 92 88]
86.6
88.0
4.882622246293481
23.84
[8.5 9.  7.8 9.2 8.8]


In [69]:
#矩阵运算
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1+arr2)
print(arr1*arr2)
print(arr1@arr2)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [73]:
#随机数字,3*4形状,范围0到10不包10,计算每列最大和每行最小,将奇数替换为-1
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print('每列最大值',np.max(arr,axis=0))
print('每行最小值',np.min(arr,axis=1))
print(np.where(arr%2==1,-1,arr))
arr[arr%2==1]=-1  #索引
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列最大值 [7 9 7 6]
每行最小值 [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [87]:
#创建1-12一维数组,转化为(3,4)二维数组,计算每行he 每列平均值,将数组展成
arr = np.arange(1,13)
print(arr)
print(np.reshape(arr,(3,4)))
arr = np.reshape(arr,(3,4))
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=0))
print(np.reshape(arr,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [92]:
#生成5*5随机数组,范围0-20,找出大于10的元素,将大于10的元素替换为0
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [100]:
 #统计,6个月销售额,计算总数,均值,方差,找出最高最低月份
 money = np.array([120,135,110,125,130,140])
 print(money)
 print(np.sum(money))
 print('%.2f'%np.mean(money))
 print('%.2f'%np.var(money))
 print(np.argmax(money)+1)
 print(np.argmin(money)+1)



[120 135 110 125 130 140]
760
126.67
97.22
6
3


In [105]:
#数组拼接,水平,垂直拼接
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate([A,B])
print(C)
print(np.reshape(C,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [114]:
#唯一值与排序,找到唯一值,并且排序,计算每个唯一值出现次数
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))

u_arry,counts = np.unique(arr,return_counts=True)
print(counts)

d = []
for i in range(len(u_arry)):
    d = d+[len(arr[arr==u_arry[i]])]
print(d)

[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


In [124]:
#给出商店5天销售额和成本,计算每天利润,计算利润平均值和标准差,找出利润最高的天数
sale = np.array([20,25,22,30,28])
raw = np.array([15,18,16,22,20])
pft = np.array(sale-raw)
print(pft)
print(np.mean(pft))
print(np.std(pft))
print(len(pft[pft==np.max(pft)]))

[5 7 6 8 8]
6.8
1.16619037896906
2
