# Pandas


## series


In [91]:
import pandas as pd
import numpy as np
#series创建
s = pd.Series([10,2,3,4,5])
print(s)
#自定义索引
# s = pd.Series([10,2,3,4,5],index=['a','b','c','d','e'])
# print(s)
#自定义name
s = pd.Series([10,2,3,4,5],index=['a','b','c','d','e'],name = '月份')
s['f']=6
s['g'] = 10
print(s)

0    10
1     2
2     3
3     4
4     5
dtype: int64
a    10
b     2
c     3
d     4
e     5
f     6
g    10
Name: 月份, dtype: int64


In [92]:
#通过字典来创建
# s= pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
# print(s)
s1 = pd.Series(s,index=['a','e'])
print(s1)

a    10
e     5
Name: 月份, dtype: int64


In [93]:
print(s)
print(s.index)
print(s.values)
print(s.shape)
print(s.ndim)
print(s.size)
print(s.dtype,s.name)
print(s.loc['b']) #显 式索引
print(s.iloc[3])  #隐式索引

a    10
b     2
c     3
d     4
e     5
f     6
g    10
Name: 月份, dtype: int64
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
[10  2  3  4  5  6 10]
(7,)
1
7
int64 月份
2
4


In [94]:
print(s.iloc[3])
print(s.at['a'])
print(s.iat[0])

4
10
10


In [95]:
#访问数据
print(s['a'])
print(s['c'])

print(s[s<4])

print(s.head()) #打印前五行
print(s.head(3)) #前三行
print(s.tail())

10
3
b    2
c    3
Name: 月份, dtype: int64
a    10
b     2
c     3
d     4
e     5
Name: 月份, dtype: int64
a    10
b     2
c     3
Name: 月份, dtype: int64
c     3
d     4
e     5
f     6
g    10
Name: 月份, dtype: int64


In [96]:
#  常见函数
#
#

s = pd.Series([10,2,np.nan,None,3,4,5],index=['a','b','c','d','e','f','g'],name='data')
print(s)

print(s.head())
s.tail(3)



a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
Name: data, dtype: float64
a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
Name: data, dtype: float64


e    3.0
f    4.0
g    5.0
Name: data, dtype: float64

In [97]:
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64

In [98]:
#获取元素个数,忽略缺失值
print(s.count())

5


In [99]:
s.keys() #有括号的是一种方法

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

In [100]:
print(s.isna())

a    False
b    False
c     True
d     True
e    False
f    False
g    False
Name: data, dtype: bool


In [101]:
s.isin([4,5,6]) #用来检查元素是否在里面

a    False
b    False
c    False
d    False
e    False
f     True
g     True
Name: data, dtype: bool

In [102]:
print(s.describe())
print(s.mean())
print(s.std())
print(s.sum())
print(s.median())
s.sort_values()
print(s.quantile(0.25))
print(s.quantile(0.75))
print(s.quantile(0.8)) #4个间隔 * 0.8 = 3.2 跳过三个间隔,第四个间隔(10-5)*0.2=1  5+1=6

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64
4.8
3.1144823004794877
24.0
4.0
3.0
5.0
6.000000000000001


In [103]:
s.sort_values()

b     2.0
e     3.0
f     4.0
g     5.0
a    10.0
c     NaN
d     NaN
Name: data, dtype: float64

In [104]:
s['h']=4
print(s)
print(s.mode())
print(s.value_counts())

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
h     4.0
Name: data, dtype: float64
0    4.0
Name: data, dtype: float64
data
4.0     2
10.0    1
2.0     1
3.0     1
5.0     1
Name: count, dtype: int64


In [105]:
s.drop_duplicates() #去重

a    10.0
b     2.0
c     NaN
e     3.0
f     4.0
g     5.0
Name: data, dtype: float64

In [106]:
s.unique()

array([10.,  2., nan,  3.,  4.,  5.])

In [107]:
print(s.nunique()) #获取去重后的个数

5


In [108]:
s.sort_index() #按索引排序

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
h     4.0
Name: data, dtype: float64

In [109]:
s.sort_values() #按值排序

b     2.0
e     3.0
f     4.0
h     4.0
g     5.0
a    10.0
c     NaN
d     NaN
Name: data, dtype: float64

## 案例分析

In [110]:
#生成10名学生数学成绩的series,50-100分,计算平均最低最高,找出高于平均的人数
np.random.seed(42)
scores = pd.Series(np.random.randint(50,101,10),index=['学生'+str(i) for i in range(1,11)])
print(scores)

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int64


In [111]:
np.random.seed(42)
values = np.random.randint(50,101,10)
index = []
for i in range(1,11):
    index.append('学生'+str(i))
print(index)
print(values)

['学生1', '学生2', '学生3', '学生4', '学生5', '学生6', '学生7', '学生8', '学生9', '学生10']
[88 78 64 92 57 70 88 68 72 60]


In [112]:
print(scores.mean())
print(scores.min())
print(scores.max())
print(scores[scores>scores.mean()])
print(len(scores[scores>scores.mean()]))

73.7
57
92
学生1    88
学生2    78
学生4    92
学生7    88
dtype: int64
4


In [113]:
import pandas as pd
import numpy as np
np.random.seed(42)
values = np.random.randint(50,101,10)
indexes = []
for i in range(1,11):
    indexes.append('学生'+str(i))
scores = pd.Series(values,indexes)
print(scores)

print(scores.mean())
print(scores.min())
print(scores.max())
print(len(scores[scores>scores.mean()]))
print(scores[scores>scores.mean()].count())

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int64
73.7
57
92
4
4


In [125]:
#给定一周温度,找出超过30°C的天数,计算平均温,从高到低排序,找出温度变化最大的两天
import pandas as pd
import numpy as np
temp = pd.Series([28,31,29,32,30,27,33],index=['周一','周二','周三','周四','周五','周六','周日'])
print(temp[temp>30].count())
print(temp.mean())
print(temp.sort_values(ascending=False))

t = abs(temp.diff())
print(t.sort_values(ascending = False).keys()[:2].tolist())
print(*(t.sort_values(ascending = False).keys()[:2].tolist()))


3
30.0
周日    33
周四    32
周二    31
周五    30
周三    29
周一    28
周六    27
dtype: int64
['周日', '周二']
周日 周二


In [130]:
#给定10个交易日股票收盘价,计算每日收益率,找出最低最高收益率的日期,计算波动率(收益率的标准差)
prices = pd.Series([102.3,103.5,105.1,104.8,106.2,107.0,106.5,108.1,109.3,110.2],index=pd.date_range('2023-01-01',periods=10))
prices.pct_change()  #percent (今天/昨天)-1
a = prices.pct_change()
print(a)
print(a.max())
print(a.idxmax())
print(a.std())

2023-01-01         NaN
2023-01-02    0.011730
2023-01-03    0.015459
2023-01-04   -0.002854
2023-01-05    0.013359
2023-01-06    0.007533
2023-01-07   -0.004673
2023-01-08    0.015023
2023-01-09    0.011101
2023-01-10    0.008234
Freq: D, dtype: float64
0.015458937198067568
2023-01-03 00:00:00
0.007373623845361105


In [152]:
 #12个月销售量,计算季度平均销售量,最高销售量月份,月环比增长率,找出连续增长超过2个月的月份
sales = pd.Series([120,135,145,160,155,170,180,175,190,200,210,220],index=pd.date_range('2022-01-01',periods=12,freq='MS'))
print(sales)
sales.resample('QS').mean() #重新采样
print("最大销售额",sales.max())
print("最大销售额月份",sales.idxmax())
print("月环比增长率",sales.pct_change())
a = sales.pct_change()
b = a>0
print(b[b.rolling(3).sum()==3].keys().tolist())

2022-01-01    120
2022-02-01    135
2022-03-01    145
2022-04-01    160
2022-05-01    155
2022-06-01    170
2022-07-01    180
2022-08-01    175
2022-09-01    190
2022-10-01    200
2022-11-01    210
2022-12-01    220
Freq: MS, dtype: int64
最大销售额 220
最大销售额月份 2022-12-01 00:00:00
月环比增长率 2022-01-01         NaN
2022-02-01    0.125000
2022-03-01    0.074074
2022-04-01    0.103448
2022-05-01   -0.031250
2022-06-01    0.096774
2022-07-01    0.058824
2022-08-01   -0.027778
2022-09-01    0.085714
2022-10-01    0.052632
2022-11-01    0.050000
2022-12-01    0.047619
Freq: MS, dtype: float64
[Timestamp('2022-04-01 00:00:00'), Timestamp('2022-11-01 00:00:00'), Timestamp('2022-12-01 00:00:00')]


In [185]:
#每小时销售额 计算每日总销售额,计算营业时间(8-10)和非营业时间销售额比例,找出销售额最高的三小时
import pandas as pd
import numpy as np
np.random.seed(42)
#print(pd.Series(np.random.randint(0,100,24)))
h = pd.Series(np.random.randint(0,100,24),index = pd.date_range('2026-01-01',periods=24,freq='h'))
print(h)
day_sales = h.resample('D').sum()
#hours_sales.between_time('8:00',"22:00")   #筛选一段时间内
b = h[(h.index.hour>=8)&(h.index.hour<=22)]
n_b = h.drop(b.index)
#print(business_hours_sales)
print("营业时间和非营业时间销售额比例",b.sum() / n_b.sum(  ))

2026-01-01 00:00:00    51
2026-01-01 01:00:00    92
2026-01-01 02:00:00    14
2026-01-01 03:00:00    71
2026-01-01 04:00:00    60
2026-01-01 05:00:00    20
2026-01-01 06:00:00    82
2026-01-01 07:00:00    86
2026-01-01 08:00:00    74
2026-01-01 09:00:00    74
2026-01-01 10:00:00    87
2026-01-01 11:00:00    99
2026-01-01 12:00:00    23
2026-01-01 13:00:00     2
2026-01-01 14:00:00    21
2026-01-01 15:00:00    52
2026-01-01 16:00:00     1
2026-01-01 17:00:00    87
2026-01-01 18:00:00    29
2026-01-01 19:00:00    37
2026-01-01 20:00:00     1
2026-01-01 21:00:00    63
2026-01-01 22:00:00    59
2026-01-01 23:00:00    20
Freq: h, dtype: int64
营业时间和非营业时间销售额比例 1.4294354838709677
